---
name: CI/CD
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'
  schedule:
    - cron: '0 4 */15 * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    name: Code check
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ ubuntu2204, ubuntu2204-ansible, ubuntu2404, ubuntu2404-ansible, debian10, debian11, debian12 ]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Change ownership
        run: |
          sudo chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE

      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.os }}/Dockerfile
          ignore: SC2086, DL3008, DL3013, DL3002, DL3007, DL3018, DL3033, SC3037, DL3059, SC2039, DL3018, DL3033, SC1091, DL3003, DL3027

  build_container:
    name: Build container
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os: [ ubuntu2204, ubuntu2204-ansible, ubuntu2404, ubuntu2404-ansible, debian10, debian11, debian12 ]
        include:
          - os: ubuntu2204
            codename: ubuntu-jammy
          - os: ubuntu2204-ansible
            codename: ubuntu-jammy-ansible
          - os: ubuntu2404-ansible
            codename: ubuntu-oracular-ansible
          - os: ubuntu2404
            codename: ubuntu-oracular            
          - os: debian10
            codename: debian-buster
          - os: debian11
            codename: debian-bullseye
          - os: debian12
            codename: debian-bookworm
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Change ownership
        run: |
          sudo chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE

      - name: Checkout the codebase
        uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses:  docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image.
        if: ${{ matrix.codename !='' }}
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ matrix.os }}/Dockerfile
          platforms: linux/amd64
          push: true
          pull: true
          tags: udienz/jenkins-slave:${{ matrix.os }},udienz/jenkins-slave:${{ matrix.codename }}

      - name: Build and push image.
        if: ${{ matrix.codename =='' }}
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ matrix.os }}/Dockerfile
          platforms: linux/amd64
          push: true
          pull: true
          tags: udienz/jenkins-slave:${{ matrix.os }}
