name: check trusty dockerfile for PR
on:
  pull_request:
    branch-ignore:
      - "main"
      - "master"
jobs:
  hadolint:
    runs-on: ["self-hosted"]
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Hadolint
       uses: hadolint/hadolint-action@v1.6.0
       with:
         dockerfile: trusty/Dockerfile
         ignore: DL3008 DL3007 DL3018 DL3033

